[theme]
base="dark"             # "light" or "dark"
primaryColor="#e32323ff"  # buttons, highlights
backgroundColor="#eef0f5ff"
secondaryBackgroundColor="#262730"
textColor="#f02424ff"
font="sans serif"       # "serif", "sans serif", or "monospace"