[theme]
base="dark"             # "light" or "dark"
primaryColor="#b31f05ff"  # buttons, highlights
backgroundColor="#eef0f5ff"
secondaryBackgroundColor="#262730"
textColor="#b31f05ff"
font="sans serif"       # "serif", "sans serif", or "monospace"