[theme]
base="dark"             # "light" or "dark"
primaryColor="#FF4B4B"  # buttons, highlights
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"       # "serif", "sans serif", or "monospace"